// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw78Zzo6w_KSk_DBiosPtQ1lVb3TQLQ68',
    appId: '1:632680854741:web:c59d4c8648b34823065e5c',
    messagingSenderId: '632680854741',
    projectId: 'wedlist-935f0',
    authDomain: 'wedlist-935f0.firebaseapp.com',
    storageBucket: 'wedlist-935f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPkzmLHn_TH8xYqhjO-3G9F9qH_ajzHvU',
    appId: '1:632680854741:android:ef21c9c3f27c718d065e5c',
    messagingSenderId: '632680854741',
    projectId: 'wedlist-935f0',
    storageBucket: 'wedlist-935f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuJwrHb36S0xveULOu6vMS6KKsUmmcxSo',
    appId: '1:632680854741:ios:3c7240e2499f757f065e5c',
    messagingSenderId: '632680854741',
    projectId: 'wedlist-935f0',
    storageBucket: 'wedlist-935f0.firebasestorage.app',
    iosBundleId: 'com.example.wedlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuJwrHb36S0xveULOu6vMS6KKsUmmcxSo',
    appId: '1:632680854741:ios:3c7240e2499f757f065e5c',
    messagingSenderId: '632680854741',
    projectId: 'wedlist-935f0',
    storageBucket: 'wedlist-935f0.firebasestorage.app',
    iosBundleId: 'com.example.wedlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw78Zzo6w_KSk_DBiosPtQ1lVb3TQLQ68',
    appId: '1:632680854741:web:93a86bfd01d206de065e5c',
    messagingSenderId: '632680854741',
    projectId: 'wedlist-935f0',
    authDomain: 'wedlist-935f0.firebaseapp.com',
    storageBucket: 'wedlist-935f0.firebasestorage.app',
  );
}
